apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: fiapstore
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  RABBITMQ_HOST: "rabbitmq"
  EmailSenderLambda__BaseUrl: "https://copwct7owsabhq2udy4ru2m4jy0eidod.lambda-url.us-east-2.on.aws/"
